using Riok.Mapperly.Abstractions;
using PhoenixKC.Infrastructure.Features.Example;
using PhoenixKC.WebAPI.Features.Example.Dtos;

namespace PhoenixKC.WebAPI.Features.Example;

[Mapper]
public static partial class ExampleMapper
{
    public static partial ExampleDto ToDto(this ExampleEntity entity); //Source-Generated by Mapperly
    public static partial IEnumerable<ExampleDto> ToDto(this IEnumerable<ExampleEntity> entities); //Source-Generated by Mapperly
    public static partial ExampleEntity ToEntity(this ExampleDto dto); //Source-Generated by Mapperly
    public static partial IEnumerable<ExampleEntity> ToEntity(this IEnumerable<ExampleDto> dtos); //Source-Generated by Mapperly
    public static partial void MapToDto(this ExampleEntity entity, ExampleDto dto); //Source-Generated by Mapperly
    public static partial void MapToEntity(this ExampleDto dto, ExampleEntity entity); //Source-Generated by Mapperly
    public static partial IQueryable<ExampleDto> ProjectToDto(this IQueryable<ExampleEntity> query); //Source-Generated by Mapperly
}