using Riok.Mapperly.Abstractions;
using PhoenixKC.WebAPI.Features.Health.Dtos;
using PhoenixKC.Infrastructure.Features.Health;

namespace PhoenixKC.WebAPI.Features.Health;

/// <summary>
/// Contains extension methods for converting between <see cref="HealthEntity"/> and <see cref="HealthDto"/>
/// </summary>
[Mapper] public static partial class HealthMapper
{
    /// <summary>
    /// Converts <paramref name="entity"/> to <see cref="HealthDto"/>
    /// </summary>
    /// <param name="entity">The entity to convert</param>
    /// <returns>The converted dto</returns>
    public static partial HealthDto ToDto(this HealthEntity entity); //Source generated by Mapperly

    /// <summary>
    /// Converts <paramref name="entities"/> to <see cref="IEnumerable{HealthDto}"/>
    /// </summary>
    /// <param name="entities">The enumerable of entities to convert</param>
    /// <returns>New enumerable with converted dtos</returns>
    public static partial IEnumerable<HealthDto> ToDto(this IEnumerable<HealthEntity> entities); //Source generated by Mapperly

    /// <summary>
    /// Converts <paramref name="dto"/> to <see cref="HealthEntity"/>
    /// </summary>
    /// <param name="dto">The dto to convert</param>
    /// <returns>The converted entity</returns>
    public static partial HealthEntity ToEntity(this HealthDto dto); //Source generated by Mapperly

    /// <summary>
    /// Converts <paramref name="dtos"/> to <see cref="IEnumerable{HealthEntity}"/>
    /// </summary>
    /// <param name="dtos">The enumerable of dtos to convert</param>
    /// <returns>New enumerable with converted entities</returns>
    public static partial IEnumerable<HealthEntity> ToEntity(this IEnumerable<HealthDto> dtos); //Source generated by Mapperly

    /// <summary>
    /// Assigns properties of the <paramref name="entity"/> to <paramref name="dto"/>
    /// </summary>
    /// <param name="entity">The source entity</param>
    /// <param name="dto">The destination dto</param>
    public static partial void MapToDto(this HealthEntity entity, HealthDto dto); //Source generated by Mapperly

    /// <summary>
    /// Assigns properties of the <paramref name="dto"/> to <paramref name="entity"/>
    /// </summary>
    /// <param name="dto">The source dto</param>
    /// <param name="entity">The destination entity</param>
    public static partial void MapToEntity(this HealthDto dto, HealthEntity entity); //Source generated by Mapperly

    /// <summary>
    /// Creates a query that retrieves neccessary properties from the database and maps them to a new <see cref="HealthDto"/>
    /// </summary>
    /// <remarks>
    /// Skips creation of <see cref="HealthEntity"/> and maps the properties directly to <see cref="HealthDto"/>.
    /// This is more efficient than retrieving the entities and then mapping them to dtos.
    /// But it works only for the simple queries.
    /// </remarks>
    /// <param name="query">The query</param>
    /// <returns>New query with <see cref="HealthDto"/> items</returns>
    public static partial IQueryable<HealthDto> ProjectToDto(this IQueryable<HealthEntity> query); //Source generated by Mapperly
}